重构检查点的存储逻辑，撞BUG上了
ArgumentException: Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type.